/**
 * Assetto Corsa ORIGINAL shared-memory struct definitions (not ACC).
 *
 * Offsets from Kunos SharedMemory.h / community pack(4) layouts ending at
 * localVelocity (physics), windDirection (graphics), and pitWindowEnd (static).
 * Memory map names remain Local\\acpmf_* — same as ACC — but SIZE differs.
 *
 * Verified sizes via ctypes pack(4): Physics 580, Graphics 296, Static 684.
 */

// --- SPageFilePhysics (original AC; ends at localVelocity[3]) ---
export const PHYSICS = {
  SIZE: 580,
  packetId:       { offset: 0, type: "i32" },
  gas:            { offset: 4, type: "f32" },
  brake:          { offset: 8, type: "f32" },
  fuel:           { offset: 12, type: "f32" },
  gear:           { offset: 16, type: "i32" },
  rpms:           { offset: 20, type: "i32" },
  steerAngle:     { offset: 24, type: "f32" },
  speedKmh:       { offset: 28, type: "f32" },
  velocityX:      { offset: 32, type: "f32" },
  velocityY:      { offset: 36, type: "f32" },
  velocityZ:      { offset: 40, type: "f32" },
  accGX:          { offset: 44, type: "f32" },
  accGY:          { offset: 48, type: "f32" },
  accGZ:          { offset: 52, type: "f32" },
  wheelSlipFL:    { offset: 56, type: "f32" },
  wheelSlipFR:    { offset: 60, type: "f32" },
  wheelSlipRL:    { offset: 64, type: "f32" },
  wheelSlipRR:    { offset: 68, type: "f32" },
  wheelLoadFL:    { offset: 72, type: "f32" },
  wheelLoadFR:    { offset: 76, type: "f32" },
  wheelLoadRL:    { offset: 80, type: "f32" },
  wheelLoadRR:    { offset: 84, type: "f32" },
  tyrePressureFL: { offset: 88, type: "f32" },
  tyrePressureFR: { offset: 92, type: "f32" },
  tyrePressureRL: { offset: 96, type: "f32" },
  tyrePressureRR: { offset: 100, type: "f32" },
  wheelRotFL:     { offset: 104, type: "f32" },
  wheelRotFR:     { offset: 108, type: "f32" },
  wheelRotRL:     { offset: 112, type: "f32" },
  wheelRotRR:     { offset: 116, type: "f32" },
  tyreWearFL:     { offset: 120, type: "f32" },
  tyreWearFR:     { offset: 124, type: "f32" },
  tyreWearRL:     { offset: 128, type: "f32" },
  tyreWearRR:     { offset: 132, type: "f32" },
  tyreCoreFL:     { offset: 152, type: "f32" },
  tyreCoreFR:     { offset: 156, type: "f32" },
  tyreCoreRL:     { offset: 160, type: "f32" },
  tyreCoreRR:     { offset: 164, type: "f32" },
  camberFL:       { offset: 168, type: "f32" },
  camberFR:       { offset: 172, type: "f32" },
  camberRL:       { offset: 176, type: "f32" },
  camberRR:       { offset: 180, type: "f32" },
  suspTravelFL:   { offset: 184, type: "f32" },
  suspTravelFR:   { offset: 188, type: "f32" },
  suspTravelRL:   { offset: 192, type: "f32" },
  suspTravelRR:   { offset: 196, type: "f32" },
  tc:             { offset: 204, type: "f32" },
  heading:        { offset: 208, type: "f32" },
  pitch:          { offset: 212, type: "f32" },
  roll:           { offset: 216, type: "f32" },
  cgHeight:       { offset: 220, type: "f32" },
  damFront:       { offset: 224, type: "f32" },
  damRear:        { offset: 228, type: "f32" },
  damLeft:        { offset: 232, type: "f32" },
  damRight:       { offset: 236, type: "f32" },
  damCentre:      { offset: 240, type: "f32" },
  abs:            { offset: 252, type: "f32" },
  rideHeightF:    { offset: 268, type: "f32" },
  rideHeightR:    { offset: 272, type: "f32" },
  airTemp:        { offset: 288, type: "f32" },
  roadTemp:       { offset: 292, type: "f32" },
  localAngularVelX: { offset: 296, type: "f32" },
  localAngularVelY: { offset: 300, type: "f32" },
  localAngularVelZ: { offset: 304, type: "f32" },
  brakeTempFL:    { offset: 348, type: "f32" },
  brakeTempFR:    { offset: 352, type: "f32" },
  brakeTempRL:    { offset: 356, type: "f32" },
  brakeTempRR:    { offset: 360, type: "f32" },
  clutch:         { offset: 364, type: "f32" },
  tyreTempInnerFL: { offset: 368, type: "f32" },
  tyreTempInnerFR: { offset: 372, type: "f32" },
  tyreTempInnerRL: { offset: 376, type: "f32" },
  tyreTempInnerRR: { offset: 380, type: "f32" },
  tyreTempMiddleFL: { offset: 384, type: "f32" },
  tyreTempMiddleFR: { offset: 388, type: "f32" },
  tyreTempMiddleRL: { offset: 392, type: "f32" },
  tyreTempMiddleRR: { offset: 396, type: "f32" },
  tyreTempOuterFL: { offset: 400, type: "f32" },
  tyreTempOuterFR: { offset: 404, type: "f32" },
  tyreTempOuterRL: { offset: 408, type: "f32" },
  tyreTempOuterRR: { offset: 412, type: "f32" },
  contactHeadingBase: { offset: 516, type: "f32" },
  brakeBias:      { offset: 564, type: "f32" },
  localVelocityX: { offset: 568, type: "f32" },
  localVelocityY: { offset: 572, type: "f32" },
  localVelocityZ: { offset: 576, type: "f32" },
} as const;

// --- SPageFileGraphic (original AC; single-car coordinates + wind) ---
export const GRAPHICS = {
  SIZE: 296,
  packetId:         { offset: 0, type: "i32" },
  status:           { offset: 4, type: "i32" },
  session:          { offset: 8, type: "i32" },
  completedLaps:    { offset: 132, type: "i32" },
  position:         { offset: 136, type: "i32" },
  iCurrentTime:     { offset: 140, type: "i32" },
  iLastTime:        { offset: 144, type: "i32" },
  iBestTime:        { offset: 148, type: "i32" },
  sessionTimeLeft:  { offset: 152, type: "f32" },
  distanceTraveled: { offset: 156, type: "f32" },
  isInPit:          { offset: 160, type: "i32" },
  currentSectorIndex: { offset: 164, type: "i32" },
  lastSectorTime:   { offset: 168, type: "i32" },
  numberOfLaps:     { offset: 172, type: "i32" },
  currentTyreCompound: { offset: 176, size: 66, type: "wstring" },
  normalizedCarPosition: { offset: 248, type: "f32" },
  // Original AC: float carCoordinates[3] (player only) — not ACC's [60][3]
  carX:             { offset: 252, type: "f32" },
  carY:             { offset: 256, type: "f32" },
  carZ:             { offset: 260, type: "f32" },
  penaltyTime:      { offset: 264, type: "f32" },
  flag:             { offset: 268, type: "i32" },
  isInPitLane:      { offset: 276, type: "i32" },
  surfaceGrip:      { offset: 280, type: "f32" },
  windSpeed:        { offset: 288, type: "f32" },
  windDirection:    { offset: 292, type: "f32" },
} as const;

// --- SPageFileStatic (original AC; trackConfiguration wchar[33], no isOnline) ---
export const STATIC = {
  SIZE: 684,
  numberOfSessions: { offset: 60, type: "i32" },
  numCars:          { offset: 64, type: "i32" },
  carModel:         { offset: 68, size: 66, type: "wstring" },
  track:            { offset: 134, size: 66, type: "wstring" },
  playerName:       { offset: 200, size: 66, type: "wstring" },
  playerSurname:    { offset: 266, size: 66, type: "wstring" },
  playerNick:       { offset: 332, size: 66, type: "wstring" },
  sectorCount:      { offset: 400, type: "i32" },
  maxRpm:           { offset: 412, type: "i32" },
  maxFuel:          { offset: 416, type: "f32" },
  suspMaxFL:        { offset: 420, type: "f32" },
  suspMaxFR:        { offset: 424, type: "f32" },
  suspMaxRL:        { offset: 428, type: "f32" },
  suspMaxRR:        { offset: 432, type: "f32" },
  tyreRadiusFL:     { offset: 436, type: "f32" },
  tyreRadiusFR:     { offset: 440, type: "f32" },
  tyreRadiusRL:     { offset: 444, type: "f32" },
  tyreRadiusRR:     { offset: 448, type: "f32" },
  trackSplineLength: { offset: 520, type: "f32" },
  pitWindowStart:   { offset: 676, type: "i32" },
  pitWindowEnd:     { offset: 680, type: "i32" },
} as const;

export const AC_STATUS = {
  AC_OFF: 0,
  AC_REPLAY: 1,
  AC_LIVE: 2,
  AC_PAUSE: 3,
} as const;

export const AC_FLAG = {
  NONE: 0,
  BLUE: 1,
  YELLOW: 2,
  BLACK: 3,
  WHITE: 4,
  CHECKERED: 5,
  PENALTY: 6,
} as const;

export const FLAG_STATUS: Record<number, string> = {
  [AC_FLAG.NONE]: "none",
  [AC_FLAG.BLUE]: "blue",
  [AC_FLAG.YELLOW]: "yellow",
  [AC_FLAG.BLACK]: "black",
  [AC_FLAG.WHITE]: "white",
  [AC_FLAG.CHECKERED]: "checkered",
  [AC_FLAG.PENALTY]: "penalty",
};
