/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameidRouteImport } from './routes/$gameid'
import { Route as AcRouteImport } from './routes/ac'
import { Route as AcEvoRouteImport } from './routes/ac-evo'
import { Route as AccRouteImport } from './routes/acc'
import { Route as DevRouteImport } from './routes/dev'
import { Route as F125RouteImport } from './routes/f125'
import { Route as Fm23RouteImport } from './routes/fm23'
import { Route as IracingRouteImport } from './routes/iracing'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LmuRouteImport } from './routes/lmu'
import { Route as GameidCarsRouteImport } from './routes/$gameid/cars'
import { Route as GameidChatsRouteImport } from './routes/$gameid/chats'
import { Route as GameidCompareRouteImport } from './routes/$gameid/compare'
import { Route as GameidDriverRouteImport } from './routes/$gameid/driver'
import { Route as GameidExperimentsRouteImport } from './routes/$gameid/experiments'
import { Route as GameidRawRouteImport } from './routes/$gameid/raw'
import { Route as GameidSessionsRouteImport } from './routes/$gameid/sessions'
import { Route as GameidTracksRouteImport } from './routes/$gameid/tracks'
import { Route as AcEvoIndexRouteImport } from './routes/ac-evo/index'
import { Route as AcEvoSetupsRouteImport } from './routes/ac-evo/setups'
import { Route as AcIndexRouteImport } from './routes/ac/index'
import { Route as AccIndexRouteImport } from './routes/acc/index'
import { Route as AccSetupsRouteImport } from './routes/acc/setups'
import { Route as F125IndexRouteImport } from './routes/f125/index'
import { Route as F125SetupsRouteImport } from './routes/f125/setups'
import { Route as F125TunesRouteImport } from './routes/f125/tunes'
import { Route as Fm23IndexRouteImport } from './routes/fm23/index'
import { Route as Fm23SetupsRouteImport } from './routes/fm23/setups'
import { Route as IracingIndexRouteImport } from './routes/iracing/index'
import { Route as LivePitRouteImport } from './routes/live.pit'
import { Route as LmuIndexRouteImport } from './routes/lmu/index'
import { Route as PortableIndexRouteImport } from './routes/portable.index'
import { Route as PortableCombo1RouteImport } from './routes/portable.combo-1'
import { Route as PortableCombo2RouteImport } from './routes/portable.combo-2'
import { Route as GameidExperimentsIndexRouteImport } from './routes/$gameid/experiments.index'
import { Route as GameidExperimentsExperimentIdRouteImport } from './routes/$gameid/experiments.$experimentId'
import { Route as GameidSessionsIndexRouteImport } from './routes/$gameid/sessions.index'
import { Route as GameidSessionsAnalyseRouteImport } from './routes/$gameid/sessions.analyse'
import { Route as GameidTracksIndexRouteImport } from './routes/$gameid/tracks.index'
import { Route as AcEvoSetupsIndexRouteImport } from './routes/ac-evo/setups/index'
import { Route as AcEvoSetupsImportRouteImport } from './routes/ac-evo/setups/import'
import { Route as AcEvoSetupsNewRouteImport } from './routes/ac-evo/setups/new'
import { Route as AccSetupsIndexRouteImport } from './routes/acc/setups/index'
import { Route as AccSetupsImportRouteImport } from './routes/acc/setups/import'
import { Route as AccSetupsNewRouteImport } from './routes/acc/setups/new'
import { Route as F125SetupsIndexRouteImport } from './routes/f125/setups/index'
import { Route as F125TunesIndexRouteImport } from './routes/f125/tunes/index'
import { Route as Fm23CarsCarOrdinalRouteImport } from './routes/fm23/cars_.$carOrdinal'
import { Route as Fm23SetupsIndexRouteImport } from './routes/fm23/setups/index'
import { Route as Fm23SetupsCatalogRouteImport } from './routes/fm23/setups/catalog'
import { Route as Fm23SetupsNewRouteImport } from './routes/fm23/setups/new'
import { Route as GameidExperimentsExperimentIdReviewRouteImport } from './routes/$gameid/experiments.$experimentId_.review'
import { Route as GameidSessionsSessionIdAnalyseRouteImport } from './routes/$gameid/sessions/$sessionId/analyse'
import { Route as GameidTracksTrackOrdinalIndexRouteImport } from './routes/$gameid/tracks.$trackOrdinal.index'
import { Route as GameidTracksTrackOrdinalTabRouteImport } from './routes/$gameid/tracks.$trackOrdinal.$tab'
import { Route as AcEvoSetupsEditTuneIdRouteImport } from './routes/ac-evo/setups/edit.$tuneId'
import { Route as AccSetupsEditTuneIdRouteImport } from './routes/acc/setups/edit.$tuneId'
import { Route as Fm23SetupsEditTuneIdRouteImport } from './routes/fm23/setups/edit.$tuneId'
import { Route as GameidSessionsSessionIdReplayLapIdRouteImport } from './routes/$gameid/sessions/$sessionId/replay/$lapId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameidRoute = GameidRouteImport.update({
  id: '/$gameid',
  path: '/$gameid',
  getParentRoute: () => rootRouteImport,
} as any)
const AcRoute = AcRouteImport.update({
  id: '/ac',
  path: '/ac',
  getParentRoute: () => rootRouteImport,
} as any)
const AcEvoRoute = AcEvoRouteImport.update({
  id: '/ac-evo',
  path: '/ac-evo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccRoute = AccRouteImport.update({
  id: '/acc',
  path: '/acc',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const F125Route = F125RouteImport.update({
  id: '/f125',
  path: '/f125',
  getParentRoute: () => rootRouteImport,
} as any)
const Fm23Route = Fm23RouteImport.update({
  id: '/fm23',
  path: '/fm23',
  getParentRoute: () => rootRouteImport,
} as any)
const IracingRoute = IracingRouteImport.update({
  id: '/iracing',
  path: '/iracing',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LmuRoute = LmuRouteImport.update({
  id: '/lmu',
  path: '/lmu',
  getParentRoute: () => rootRouteImport,
} as any)
const GameidCarsRoute = GameidCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => GameidRoute,
} as any)
const GameidChatsRoute = GameidChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => GameidRoute,
} as any)
const GameidCompareRoute = GameidCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => GameidRoute,
} as any)
const GameidDriverRoute = GameidDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => GameidRoute,
} as any)
const GameidExperimentsRoute = GameidExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => GameidRoute,
} as any)
const GameidRawRoute = GameidRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => GameidRoute,
} as any)
const GameidSessionsRoute = GameidSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => GameidRoute,
} as any)
const GameidTracksRoute = GameidTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => GameidRoute,
} as any)
const AcEvoIndexRoute = AcEvoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoSetupsRoute = AcEvoSetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcIndexRoute = AcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcRoute,
} as any)
const AccIndexRoute = AccIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccRoute,
} as any)
const AccSetupsRoute = AccSetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => AccRoute,
} as any)
const F125IndexRoute = F125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125Route,
} as any)
const F125SetupsRoute = F125SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => F125Route,
} as any)
const F125TunesRoute = F125TunesRouteImport.update({
  id: '/tunes',
  path: '/tunes',
  getParentRoute: () => F125Route,
} as any)
const Fm23IndexRoute = Fm23IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SetupsRoute = Fm23SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => Fm23Route,
} as any)
const IracingIndexRoute = IracingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IracingRoute,
} as any)
const LivePitRoute = LivePitRouteImport.update({
  id: '/pit',
  path: '/pit',
  getParentRoute: () => LiveRoute,
} as any)
const LmuIndexRoute = LmuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LmuRoute,
} as any)
const PortableIndexRoute = PortableIndexRouteImport.update({
  id: '/portable/',
  path: '/portable/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortableCombo1Route = PortableCombo1RouteImport.update({
  id: '/portable/combo-1',
  path: '/portable/combo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const PortableCombo2Route = PortableCombo2RouteImport.update({
  id: '/portable/combo-2',
  path: '/portable/combo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const GameidExperimentsIndexRoute = GameidExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameidExperimentsRoute,
} as any)
const GameidExperimentsExperimentIdRoute =
  GameidExperimentsExperimentIdRouteImport.update({
    id: '/$experimentId',
    path: '/$experimentId',
    getParentRoute: () => GameidExperimentsRoute,
  } as any)
const GameidSessionsIndexRoute = GameidSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameidSessionsRoute,
} as any)
const GameidSessionsAnalyseRoute = GameidSessionsAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => GameidSessionsRoute,
} as any)
const GameidTracksIndexRoute = GameidTracksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameidTracksRoute,
} as any)
const AcEvoSetupsIndexRoute = AcEvoSetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AcEvoSetupsImportRoute = AcEvoSetupsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AcEvoSetupsNewRoute = AcEvoSetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AccSetupsIndexRoute = AccSetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AccSetupsImportRoute = AccSetupsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AccSetupsRoute,
} as any)
const AccSetupsNewRoute = AccSetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccSetupsRoute,
} as any)
const F125SetupsIndexRoute = F125SetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125SetupsRoute,
} as any)
const F125TunesIndexRoute = F125TunesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125TunesRoute,
} as any)
const Fm23CarsCarOrdinalRoute = Fm23CarsCarOrdinalRouteImport.update({
  id: '/cars_/$carOrdinal',
  path: '/cars/$carOrdinal',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SetupsIndexRoute = Fm23SetupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsCatalogRoute = Fm23SetupsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const Fm23SetupsNewRoute = Fm23SetupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const GameidExperimentsExperimentIdReviewRoute =
  GameidExperimentsExperimentIdReviewRouteImport.update({
    id: '/$experimentId_/review',
    path: '/$experimentId/review',
    getParentRoute: () => GameidExperimentsRoute,
  } as any)
const GameidSessionsSessionIdAnalyseRoute =
  GameidSessionsSessionIdAnalyseRouteImport.update({
    id: '/$sessionId/analyse',
    path: '/$sessionId/analyse',
    getParentRoute: () => GameidSessionsRoute,
  } as any)
const GameidTracksTrackOrdinalIndexRoute =
  GameidTracksTrackOrdinalIndexRouteImport.update({
    id: '/$trackOrdinal/',
    path: '/$trackOrdinal/',
    getParentRoute: () => GameidTracksRoute,
  } as any)
const GameidTracksTrackOrdinalTabRoute =
  GameidTracksTrackOrdinalTabRouteImport.update({
    id: '/$trackOrdinal/$tab',
    path: '/$trackOrdinal/$tab',
    getParentRoute: () => GameidTracksRoute,
  } as any)
const AcEvoSetupsEditTuneIdRoute = AcEvoSetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => AcEvoSetupsRoute,
} as any)
const AccSetupsEditTuneIdRoute = AccSetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => AccSetupsRoute,
} as any)
const Fm23SetupsEditTuneIdRoute = Fm23SetupsEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => Fm23SetupsRoute,
} as any)
const GameidSessionsSessionIdReplayLapIdRoute =
  GameidSessionsSessionIdReplayLapIdRouteImport.update({
    id: '/$sessionId/replay/$lapId',
    path: '/$sessionId/replay/$lapId',
    getParentRoute: () => GameidSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$gameid': typeof GameidRouteWithChildren
  '/ac': typeof AcRouteWithChildren
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/iracing': typeof IracingRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/lmu': typeof LmuRouteWithChildren
  '/$gameid/cars': typeof GameidCarsRoute
  '/$gameid/chats': typeof GameidChatsRoute
  '/$gameid/compare': typeof GameidCompareRoute
  '/$gameid/driver': typeof GameidDriverRoute
  '/$gameid/experiments': typeof GameidExperimentsRouteWithChildren
  '/$gameid/raw': typeof GameidRawRoute
  '/$gameid/sessions': typeof GameidSessionsRouteWithChildren
  '/$gameid/tracks': typeof GameidTracksRouteWithChildren
  '/ac-evo/setups': typeof AcEvoSetupsRouteWithChildren
  '/acc/setups': typeof AccSetupsRouteWithChildren
  '/f125/setups': typeof F125SetupsRouteWithChildren
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/setups': typeof Fm23SetupsRouteWithChildren
  '/live/pit': typeof LivePitRoute
  '/portable/combo-1': typeof PortableCombo1Route
  '/portable/combo-2': typeof PortableCombo2Route
  '/ac-evo/': typeof AcEvoIndexRoute
  '/ac/': typeof AcIndexRoute
  '/acc/': typeof AccIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/iracing/': typeof IracingIndexRoute
  '/lmu/': typeof LmuIndexRoute
  '/portable/': typeof PortableIndexRoute
  '/$gameid/experiments/$experimentId': typeof GameidExperimentsExperimentIdRoute
  '/$gameid/sessions/analyse': typeof GameidSessionsAnalyseRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/$gameid/experiments/': typeof GameidExperimentsIndexRoute
  '/$gameid/sessions/': typeof GameidSessionsIndexRoute
  '/$gameid/tracks/': typeof GameidTracksIndexRoute
  '/ac-evo/setups/': typeof AcEvoSetupsIndexRoute
  '/acc/setups/': typeof AccSetupsIndexRoute
  '/f125/setups/': typeof F125SetupsIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setups/': typeof Fm23SetupsIndexRoute
  '/$gameid/experiments/$experimentId/review': typeof GameidExperimentsExperimentIdReviewRoute
  '/$gameid/sessions/$sessionId/analyse': typeof GameidSessionsSessionIdAnalyseRoute
  '/$gameid/tracks/$trackOrdinal/$tab': typeof GameidTracksTrackOrdinalTabRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/$gameid/tracks/$trackOrdinal/': typeof GameidTracksTrackOrdinalIndexRoute
  '/$gameid/sessions/$sessionId/replay/$lapId': typeof GameidSessionsSessionIdReplayLapIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$gameid': typeof GameidRouteWithChildren
  '/dev': typeof DevRoute
  '/live': typeof LiveRouteWithChildren
  '/$gameid/cars': typeof GameidCarsRoute
  '/$gameid/chats': typeof GameidChatsRoute
  '/$gameid/compare': typeof GameidCompareRoute
  '/$gameid/driver': typeof GameidDriverRoute
  '/$gameid/raw': typeof GameidRawRoute
  '/live/pit': typeof LivePitRoute
  '/portable/combo-1': typeof PortableCombo1Route
  '/portable/combo-2': typeof PortableCombo2Route
  '/ac-evo': typeof AcEvoIndexRoute
  '/ac': typeof AcIndexRoute
  '/acc': typeof AccIndexRoute
  '/f125': typeof F125IndexRoute
  '/fm23': typeof Fm23IndexRoute
  '/iracing': typeof IracingIndexRoute
  '/lmu': typeof LmuIndexRoute
  '/portable': typeof PortableIndexRoute
  '/$gameid/experiments/$experimentId': typeof GameidExperimentsExperimentIdRoute
  '/$gameid/sessions/analyse': typeof GameidSessionsAnalyseRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/$gameid/experiments': typeof GameidExperimentsIndexRoute
  '/$gameid/sessions': typeof GameidSessionsIndexRoute
  '/$gameid/tracks': typeof GameidTracksIndexRoute
  '/ac-evo/setups': typeof AcEvoSetupsIndexRoute
  '/acc/setups': typeof AccSetupsIndexRoute
  '/f125/setups': typeof F125SetupsIndexRoute
  '/f125/tunes': typeof F125TunesIndexRoute
  '/fm23/setups': typeof Fm23SetupsIndexRoute
  '/$gameid/experiments/$experimentId/review': typeof GameidExperimentsExperimentIdReviewRoute
  '/$gameid/sessions/$sessionId/analyse': typeof GameidSessionsSessionIdAnalyseRoute
  '/$gameid/tracks/$trackOrdinal/$tab': typeof GameidTracksTrackOrdinalTabRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/$gameid/tracks/$trackOrdinal': typeof GameidTracksTrackOrdinalIndexRoute
  '/$gameid/sessions/$sessionId/replay/$lapId': typeof GameidSessionsSessionIdReplayLapIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$gameid': typeof GameidRouteWithChildren
  '/ac': typeof AcRouteWithChildren
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/iracing': typeof IracingRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/lmu': typeof LmuRouteWithChildren
  '/$gameid/cars': typeof GameidCarsRoute
  '/$gameid/chats': typeof GameidChatsRoute
  '/$gameid/compare': typeof GameidCompareRoute
  '/$gameid/driver': typeof GameidDriverRoute
  '/$gameid/experiments': typeof GameidExperimentsRouteWithChildren
  '/$gameid/raw': typeof GameidRawRoute
  '/$gameid/sessions': typeof GameidSessionsRouteWithChildren
  '/$gameid/tracks': typeof GameidTracksRouteWithChildren
  '/ac-evo/setups': typeof AcEvoSetupsRouteWithChildren
  '/acc/setups': typeof AccSetupsRouteWithChildren
  '/f125/setups': typeof F125SetupsRouteWithChildren
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/setups': typeof Fm23SetupsRouteWithChildren
  '/live/pit': typeof LivePitRoute
  '/portable/combo-1': typeof PortableCombo1Route
  '/portable/combo-2': typeof PortableCombo2Route
  '/ac-evo/': typeof AcEvoIndexRoute
  '/ac/': typeof AcIndexRoute
  '/acc/': typeof AccIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/iracing/': typeof IracingIndexRoute
  '/lmu/': typeof LmuIndexRoute
  '/portable/': typeof PortableIndexRoute
  '/$gameid/experiments/$experimentId': typeof GameidExperimentsExperimentIdRoute
  '/$gameid/sessions/analyse': typeof GameidSessionsAnalyseRoute
  '/ac-evo/setups/import': typeof AcEvoSetupsImportRoute
  '/ac-evo/setups/new': typeof AcEvoSetupsNewRoute
  '/acc/setups/import': typeof AccSetupsImportRoute
  '/acc/setups/new': typeof AccSetupsNewRoute
  '/fm23/cars_/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/setups/catalog': typeof Fm23SetupsCatalogRoute
  '/fm23/setups/new': typeof Fm23SetupsNewRoute
  '/$gameid/experiments/': typeof GameidExperimentsIndexRoute
  '/$gameid/sessions/': typeof GameidSessionsIndexRoute
  '/$gameid/tracks/': typeof GameidTracksIndexRoute
  '/ac-evo/setups/': typeof AcEvoSetupsIndexRoute
  '/acc/setups/': typeof AccSetupsIndexRoute
  '/f125/setups/': typeof F125SetupsIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setups/': typeof Fm23SetupsIndexRoute
  '/$gameid/experiments/$experimentId_/review': typeof GameidExperimentsExperimentIdReviewRoute
  '/$gameid/sessions/$sessionId/analyse': typeof GameidSessionsSessionIdAnalyseRoute
  '/$gameid/tracks/$trackOrdinal/$tab': typeof GameidTracksTrackOrdinalTabRoute
  '/ac-evo/setups/edit/$tuneId': typeof AcEvoSetupsEditTuneIdRoute
  '/acc/setups/edit/$tuneId': typeof AccSetupsEditTuneIdRoute
  '/fm23/setups/edit/$tuneId': typeof Fm23SetupsEditTuneIdRoute
  '/$gameid/tracks/$trackOrdinal/': typeof GameidTracksTrackOrdinalIndexRoute
  '/$gameid/sessions/$sessionId/replay/$lapId': typeof GameidSessionsSessionIdReplayLapIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$gameid'
    | '/ac'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/iracing'
    | '/live'
    | '/lmu'
    | '/$gameid/cars'
    | '/$gameid/chats'
    | '/$gameid/compare'
    | '/$gameid/driver'
    | '/$gameid/experiments'
    | '/$gameid/raw'
    | '/$gameid/sessions'
    | '/$gameid/tracks'
    | '/ac-evo/setups'
    | '/acc/setups'
    | '/f125/setups'
    | '/f125/tunes'
    | '/fm23/setups'
    | '/live/pit'
    | '/portable/combo-1'
    | '/portable/combo-2'
    | '/ac-evo/'
    | '/ac/'
    | '/acc/'
    | '/f125/'
    | '/fm23/'
    | '/iracing/'
    | '/lmu/'
    | '/portable/'
    | '/$gameid/experiments/$experimentId'
    | '/$gameid/sessions/analyse'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/$gameid/experiments/'
    | '/$gameid/sessions/'
    | '/$gameid/tracks/'
    | '/ac-evo/setups/'
    | '/acc/setups/'
    | '/f125/setups/'
    | '/f125/tunes/'
    | '/fm23/setups/'
    | '/$gameid/experiments/$experimentId/review'
    | '/$gameid/sessions/$sessionId/analyse'
    | '/$gameid/tracks/$trackOrdinal/$tab'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/setups/edit/$tuneId'
    | '/fm23/setups/edit/$tuneId'
    | '/$gameid/tracks/$trackOrdinal/'
    | '/$gameid/sessions/$sessionId/replay/$lapId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$gameid'
    | '/dev'
    | '/live'
    | '/$gameid/cars'
    | '/$gameid/chats'
    | '/$gameid/compare'
    | '/$gameid/driver'
    | '/$gameid/raw'
    | '/live/pit'
    | '/portable/combo-1'
    | '/portable/combo-2'
    | '/ac-evo'
    | '/ac'
    | '/acc'
    | '/f125'
    | '/fm23'
    | '/iracing'
    | '/lmu'
    | '/portable'
    | '/$gameid/experiments/$experimentId'
    | '/$gameid/sessions/analyse'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/$gameid/experiments'
    | '/$gameid/sessions'
    | '/$gameid/tracks'
    | '/ac-evo/setups'
    | '/acc/setups'
    | '/f125/setups'
    | '/f125/tunes'
    | '/fm23/setups'
    | '/$gameid/experiments/$experimentId/review'
    | '/$gameid/sessions/$sessionId/analyse'
    | '/$gameid/tracks/$trackOrdinal/$tab'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/setups/edit/$tuneId'
    | '/fm23/setups/edit/$tuneId'
    | '/$gameid/tracks/$trackOrdinal'
    | '/$gameid/sessions/$sessionId/replay/$lapId'
  id:
    | '__root__'
    | '/'
    | '/$gameid'
    | '/ac'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/iracing'
    | '/live'
    | '/lmu'
    | '/$gameid/cars'
    | '/$gameid/chats'
    | '/$gameid/compare'
    | '/$gameid/driver'
    | '/$gameid/experiments'
    | '/$gameid/raw'
    | '/$gameid/sessions'
    | '/$gameid/tracks'
    | '/ac-evo/setups'
    | '/acc/setups'
    | '/f125/setups'
    | '/f125/tunes'
    | '/fm23/setups'
    | '/live/pit'
    | '/portable/combo-1'
    | '/portable/combo-2'
    | '/ac-evo/'
    | '/ac/'
    | '/acc/'
    | '/f125/'
    | '/fm23/'
    | '/iracing/'
    | '/lmu/'
    | '/portable/'
    | '/$gameid/experiments/$experimentId'
    | '/$gameid/sessions/analyse'
    | '/ac-evo/setups/import'
    | '/ac-evo/setups/new'
    | '/acc/setups/import'
    | '/acc/setups/new'
    | '/fm23/cars_/$carOrdinal'
    | '/fm23/setups/catalog'
    | '/fm23/setups/new'
    | '/$gameid/experiments/'
    | '/$gameid/sessions/'
    | '/$gameid/tracks/'
    | '/ac-evo/setups/'
    | '/acc/setups/'
    | '/f125/setups/'
    | '/f125/tunes/'
    | '/fm23/setups/'
    | '/$gameid/experiments/$experimentId_/review'
    | '/$gameid/sessions/$sessionId/analyse'
    | '/$gameid/tracks/$trackOrdinal/$tab'
    | '/ac-evo/setups/edit/$tuneId'
    | '/acc/setups/edit/$tuneId'
    | '/fm23/setups/edit/$tuneId'
    | '/$gameid/tracks/$trackOrdinal/'
    | '/$gameid/sessions/$sessionId/replay/$lapId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameidRoute: typeof GameidRouteWithChildren
  AcRoute: typeof AcRouteWithChildren
  AcEvoRoute: typeof AcEvoRouteWithChildren
  AccRoute: typeof AccRouteWithChildren
  DevRoute: typeof DevRoute
  F125Route: typeof F125RouteWithChildren
  Fm23Route: typeof Fm23RouteWithChildren
  IracingRoute: typeof IracingRouteWithChildren
  LiveRoute: typeof LiveRouteWithChildren
  LmuRoute: typeof LmuRouteWithChildren
  PortableCombo1Route: typeof PortableCombo1Route
  PortableCombo2Route: typeof PortableCombo2Route
  PortableIndexRoute: typeof PortableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameid': {
      id: '/$gameid'
      path: '/$gameid'
      fullPath: '/$gameid'
      preLoaderRoute: typeof GameidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac': {
      id: '/ac'
      path: '/ac'
      fullPath: '/ac'
      preLoaderRoute: typeof AcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac-evo': {
      id: '/ac-evo'
      path: '/ac-evo'
      fullPath: '/ac-evo'
      preLoaderRoute: typeof AcEvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc': {
      id: '/acc'
      path: '/acc'
      fullPath: '/acc'
      preLoaderRoute: typeof AccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f125': {
      id: '/f125'
      path: '/f125'
      fullPath: '/f125'
      preLoaderRoute: typeof F125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fm23': {
      id: '/fm23'
      path: '/fm23'
      fullPath: '/fm23'
      preLoaderRoute: typeof Fm23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iracing': {
      id: '/iracing'
      path: '/iracing'
      fullPath: '/iracing'
      preLoaderRoute: typeof IracingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lmu': {
      id: '/lmu'
      path: '/lmu'
      fullPath: '/lmu'
      preLoaderRoute: typeof LmuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameid/cars': {
      id: '/$gameid/cars'
      path: '/cars'
      fullPath: '/$gameid/cars'
      preLoaderRoute: typeof GameidCarsRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/chats': {
      id: '/$gameid/chats'
      path: '/chats'
      fullPath: '/$gameid/chats'
      preLoaderRoute: typeof GameidChatsRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/compare': {
      id: '/$gameid/compare'
      path: '/compare'
      fullPath: '/$gameid/compare'
      preLoaderRoute: typeof GameidCompareRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/driver': {
      id: '/$gameid/driver'
      path: '/driver'
      fullPath: '/$gameid/driver'
      preLoaderRoute: typeof GameidDriverRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/experiments': {
      id: '/$gameid/experiments'
      path: '/experiments'
      fullPath: '/$gameid/experiments'
      preLoaderRoute: typeof GameidExperimentsRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/raw': {
      id: '/$gameid/raw'
      path: '/raw'
      fullPath: '/$gameid/raw'
      preLoaderRoute: typeof GameidRawRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/sessions': {
      id: '/$gameid/sessions'
      path: '/sessions'
      fullPath: '/$gameid/sessions'
      preLoaderRoute: typeof GameidSessionsRouteImport
      parentRoute: typeof GameidRoute
    }
    '/$gameid/tracks': {
      id: '/$gameid/tracks'
      path: '/tracks'
      fullPath: '/$gameid/tracks'
      preLoaderRoute: typeof GameidTracksRouteImport
      parentRoute: typeof GameidRoute
    }
    '/ac-evo/': {
      id: '/ac-evo/'
      path: '/'
      fullPath: '/ac-evo/'
      preLoaderRoute: typeof AcEvoIndexRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/setups': {
      id: '/ac-evo/setups'
      path: '/setups'
      fullPath: '/ac-evo/setups'
      preLoaderRoute: typeof AcEvoSetupsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac/': {
      id: '/ac/'
      path: '/'
      fullPath: '/ac/'
      preLoaderRoute: typeof AcIndexRouteImport
      parentRoute: typeof AcRoute
    }
    '/acc/': {
      id: '/acc/'
      path: '/'
      fullPath: '/acc/'
      preLoaderRoute: typeof AccIndexRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/setups': {
      id: '/acc/setups'
      path: '/setups'
      fullPath: '/acc/setups'
      preLoaderRoute: typeof AccSetupsRouteImport
      parentRoute: typeof AccRoute
    }
    '/f125/': {
      id: '/f125/'
      path: '/'
      fullPath: '/f125/'
      preLoaderRoute: typeof F125IndexRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/setups': {
      id: '/f125/setups'
      path: '/setups'
      fullPath: '/f125/setups'
      preLoaderRoute: typeof F125SetupsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/tunes': {
      id: '/f125/tunes'
      path: '/tunes'
      fullPath: '/f125/tunes'
      preLoaderRoute: typeof F125TunesRouteImport
      parentRoute: typeof F125Route
    }
    '/fm23/': {
      id: '/fm23/'
      path: '/'
      fullPath: '/fm23/'
      preLoaderRoute: typeof Fm23IndexRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/setups': {
      id: '/fm23/setups'
      path: '/setups'
      fullPath: '/fm23/setups'
      preLoaderRoute: typeof Fm23SetupsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/iracing/': {
      id: '/iracing/'
      path: '/'
      fullPath: '/iracing/'
      preLoaderRoute: typeof IracingIndexRouteImport
      parentRoute: typeof IracingRoute
    }
    '/live/pit': {
      id: '/live/pit'
      path: '/pit'
      fullPath: '/live/pit'
      preLoaderRoute: typeof LivePitRouteImport
      parentRoute: typeof LiveRoute
    }
    '/lmu/': {
      id: '/lmu/'
      path: '/'
      fullPath: '/lmu/'
      preLoaderRoute: typeof LmuIndexRouteImport
      parentRoute: typeof LmuRoute
    }
    '/portable/': {
      id: '/portable/'
      path: '/portable'
      fullPath: '/portable/'
      preLoaderRoute: typeof PortableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portable/combo-1': {
      id: '/portable/combo-1'
      path: '/portable/combo-1'
      fullPath: '/portable/combo-1'
      preLoaderRoute: typeof PortableCombo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portable/combo-2': {
      id: '/portable/combo-2'
      path: '/portable/combo-2'
      fullPath: '/portable/combo-2'
      preLoaderRoute: typeof PortableCombo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$gameid/experiments/': {
      id: '/$gameid/experiments/'
      path: '/'
      fullPath: '/$gameid/experiments/'
      preLoaderRoute: typeof GameidExperimentsIndexRouteImport
      parentRoute: typeof GameidExperimentsRoute
    }
    '/$gameid/experiments/$experimentId': {
      id: '/$gameid/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/$gameid/experiments/$experimentId'
      preLoaderRoute: typeof GameidExperimentsExperimentIdRouteImport
      parentRoute: typeof GameidExperimentsRoute
    }
    '/$gameid/sessions/': {
      id: '/$gameid/sessions/'
      path: '/'
      fullPath: '/$gameid/sessions/'
      preLoaderRoute: typeof GameidSessionsIndexRouteImport
      parentRoute: typeof GameidSessionsRoute
    }
    '/$gameid/sessions/analyse': {
      id: '/$gameid/sessions/analyse'
      path: '/analyse'
      fullPath: '/$gameid/sessions/analyse'
      preLoaderRoute: typeof GameidSessionsAnalyseRouteImport
      parentRoute: typeof GameidSessionsRoute
    }
    '/$gameid/tracks/': {
      id: '/$gameid/tracks/'
      path: '/'
      fullPath: '/$gameid/tracks/'
      preLoaderRoute: typeof GameidTracksIndexRouteImport
      parentRoute: typeof GameidTracksRoute
    }
    '/ac-evo/setups/': {
      id: '/ac-evo/setups/'
      path: '/'
      fullPath: '/ac-evo/setups/'
      preLoaderRoute: typeof AcEvoSetupsIndexRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/ac-evo/setups/import': {
      id: '/ac-evo/setups/import'
      path: '/import'
      fullPath: '/ac-evo/setups/import'
      preLoaderRoute: typeof AcEvoSetupsImportRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/ac-evo/setups/new': {
      id: '/ac-evo/setups/new'
      path: '/new'
      fullPath: '/ac-evo/setups/new'
      preLoaderRoute: typeof AcEvoSetupsNewRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/acc/setups/': {
      id: '/acc/setups/'
      path: '/'
      fullPath: '/acc/setups/'
      preLoaderRoute: typeof AccSetupsIndexRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/acc/setups/import': {
      id: '/acc/setups/import'
      path: '/import'
      fullPath: '/acc/setups/import'
      preLoaderRoute: typeof AccSetupsImportRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/acc/setups/new': {
      id: '/acc/setups/new'
      path: '/new'
      fullPath: '/acc/setups/new'
      preLoaderRoute: typeof AccSetupsNewRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/f125/setups/': {
      id: '/f125/setups/'
      path: '/'
      fullPath: '/f125/setups/'
      preLoaderRoute: typeof F125SetupsIndexRouteImport
      parentRoute: typeof F125SetupsRoute
    }
    '/f125/tunes/': {
      id: '/f125/tunes/'
      path: '/'
      fullPath: '/f125/tunes/'
      preLoaderRoute: typeof F125TunesIndexRouteImport
      parentRoute: typeof F125TunesRoute
    }
    '/fm23/cars_/$carOrdinal': {
      id: '/fm23/cars_/$carOrdinal'
      path: '/cars/$carOrdinal'
      fullPath: '/fm23/cars/$carOrdinal'
      preLoaderRoute: typeof Fm23CarsCarOrdinalRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/setups/': {
      id: '/fm23/setups/'
      path: '/'
      fullPath: '/fm23/setups/'
      preLoaderRoute: typeof Fm23SetupsIndexRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/catalog': {
      id: '/fm23/setups/catalog'
      path: '/catalog'
      fullPath: '/fm23/setups/catalog'
      preLoaderRoute: typeof Fm23SetupsCatalogRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/fm23/setups/new': {
      id: '/fm23/setups/new'
      path: '/new'
      fullPath: '/fm23/setups/new'
      preLoaderRoute: typeof Fm23SetupsNewRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/$gameid/experiments/$experimentId_/review': {
      id: '/$gameid/experiments/$experimentId_/review'
      path: '/$experimentId/review'
      fullPath: '/$gameid/experiments/$experimentId/review'
      preLoaderRoute: typeof GameidExperimentsExperimentIdReviewRouteImport
      parentRoute: typeof GameidExperimentsRoute
    }
    '/$gameid/sessions/$sessionId/analyse': {
      id: '/$gameid/sessions/$sessionId/analyse'
      path: '/$sessionId/analyse'
      fullPath: '/$gameid/sessions/$sessionId/analyse'
      preLoaderRoute: typeof GameidSessionsSessionIdAnalyseRouteImport
      parentRoute: typeof GameidSessionsRoute
    }
    '/$gameid/tracks/$trackOrdinal/': {
      id: '/$gameid/tracks/$trackOrdinal/'
      path: '/$trackOrdinal'
      fullPath: '/$gameid/tracks/$trackOrdinal/'
      preLoaderRoute: typeof GameidTracksTrackOrdinalIndexRouteImport
      parentRoute: typeof GameidTracksRoute
    }
    '/$gameid/tracks/$trackOrdinal/$tab': {
      id: '/$gameid/tracks/$trackOrdinal/$tab'
      path: '/$trackOrdinal/$tab'
      fullPath: '/$gameid/tracks/$trackOrdinal/$tab'
      preLoaderRoute: typeof GameidTracksTrackOrdinalTabRouteImport
      parentRoute: typeof GameidTracksRoute
    }
    '/ac-evo/setups/edit/$tuneId': {
      id: '/ac-evo/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/ac-evo/setups/edit/$tuneId'
      preLoaderRoute: typeof AcEvoSetupsEditTuneIdRouteImport
      parentRoute: typeof AcEvoSetupsRoute
    }
    '/acc/setups/edit/$tuneId': {
      id: '/acc/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/acc/setups/edit/$tuneId'
      preLoaderRoute: typeof AccSetupsEditTuneIdRouteImport
      parentRoute: typeof AccSetupsRoute
    }
    '/fm23/setups/edit/$tuneId': {
      id: '/fm23/setups/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/fm23/setups/edit/$tuneId'
      preLoaderRoute: typeof Fm23SetupsEditTuneIdRouteImport
      parentRoute: typeof Fm23SetupsRoute
    }
    '/$gameid/sessions/$sessionId/replay/$lapId': {
      id: '/$gameid/sessions/$sessionId/replay/$lapId'
      path: '/$sessionId/replay/$lapId'
      fullPath: '/$gameid/sessions/$sessionId/replay/$lapId'
      preLoaderRoute: typeof GameidSessionsSessionIdReplayLapIdRouteImport
      parentRoute: typeof GameidSessionsRoute
    }
  }
}

interface GameidExperimentsRouteChildren {
  GameidExperimentsExperimentIdRoute: typeof GameidExperimentsExperimentIdRoute
  GameidExperimentsIndexRoute: typeof GameidExperimentsIndexRoute
  GameidExperimentsExperimentIdReviewRoute: typeof GameidExperimentsExperimentIdReviewRoute
}

const GameidExperimentsRouteChildren: GameidExperimentsRouteChildren = {
  GameidExperimentsExperimentIdRoute: GameidExperimentsExperimentIdRoute,
  GameidExperimentsIndexRoute: GameidExperimentsIndexRoute,
  GameidExperimentsExperimentIdReviewRoute:
    GameidExperimentsExperimentIdReviewRoute,
}

const GameidExperimentsRouteWithChildren =
  GameidExperimentsRoute._addFileChildren(GameidExperimentsRouteChildren)

interface GameidSessionsRouteChildren {
  GameidSessionsAnalyseRoute: typeof GameidSessionsAnalyseRoute
  GameidSessionsIndexRoute: typeof GameidSessionsIndexRoute
  GameidSessionsSessionIdAnalyseRoute: typeof GameidSessionsSessionIdAnalyseRoute
  GameidSessionsSessionIdReplayLapIdRoute: typeof GameidSessionsSessionIdReplayLapIdRoute
}

const GameidSessionsRouteChildren: GameidSessionsRouteChildren = {
  GameidSessionsAnalyseRoute: GameidSessionsAnalyseRoute,
  GameidSessionsIndexRoute: GameidSessionsIndexRoute,
  GameidSessionsSessionIdAnalyseRoute: GameidSessionsSessionIdAnalyseRoute,
  GameidSessionsSessionIdReplayLapIdRoute:
    GameidSessionsSessionIdReplayLapIdRoute,
}

const GameidSessionsRouteWithChildren = GameidSessionsRoute._addFileChildren(
  GameidSessionsRouteChildren,
)

interface GameidTracksRouteChildren {
  GameidTracksIndexRoute: typeof GameidTracksIndexRoute
  GameidTracksTrackOrdinalTabRoute: typeof GameidTracksTrackOrdinalTabRoute
  GameidTracksTrackOrdinalIndexRoute: typeof GameidTracksTrackOrdinalIndexRoute
}

const GameidTracksRouteChildren: GameidTracksRouteChildren = {
  GameidTracksIndexRoute: GameidTracksIndexRoute,
  GameidTracksTrackOrdinalTabRoute: GameidTracksTrackOrdinalTabRoute,
  GameidTracksTrackOrdinalIndexRoute: GameidTracksTrackOrdinalIndexRoute,
}

const GameidTracksRouteWithChildren = GameidTracksRoute._addFileChildren(
  GameidTracksRouteChildren,
)

interface GameidRouteChildren {
  GameidCarsRoute: typeof GameidCarsRoute
  GameidChatsRoute: typeof GameidChatsRoute
  GameidCompareRoute: typeof GameidCompareRoute
  GameidDriverRoute: typeof GameidDriverRoute
  GameidExperimentsRoute: typeof GameidExperimentsRouteWithChildren
  GameidRawRoute: typeof GameidRawRoute
  GameidSessionsRoute: typeof GameidSessionsRouteWithChildren
  GameidTracksRoute: typeof GameidTracksRouteWithChildren
}

const GameidRouteChildren: GameidRouteChildren = {
  GameidCarsRoute: GameidCarsRoute,
  GameidChatsRoute: GameidChatsRoute,
  GameidCompareRoute: GameidCompareRoute,
  GameidDriverRoute: GameidDriverRoute,
  GameidExperimentsRoute: GameidExperimentsRouteWithChildren,
  GameidRawRoute: GameidRawRoute,
  GameidSessionsRoute: GameidSessionsRouteWithChildren,
  GameidTracksRoute: GameidTracksRouteWithChildren,
}

const GameidRouteWithChildren =
  GameidRoute._addFileChildren(GameidRouteChildren)

interface AcRouteChildren {
  AcIndexRoute: typeof AcIndexRoute
}

const AcRouteChildren: AcRouteChildren = {
  AcIndexRoute: AcIndexRoute,
}

const AcRouteWithChildren = AcRoute._addFileChildren(AcRouteChildren)

interface AcEvoSetupsRouteChildren {
  AcEvoSetupsImportRoute: typeof AcEvoSetupsImportRoute
  AcEvoSetupsNewRoute: typeof AcEvoSetupsNewRoute
  AcEvoSetupsIndexRoute: typeof AcEvoSetupsIndexRoute
  AcEvoSetupsEditTuneIdRoute: typeof AcEvoSetupsEditTuneIdRoute
}

const AcEvoSetupsRouteChildren: AcEvoSetupsRouteChildren = {
  AcEvoSetupsImportRoute: AcEvoSetupsImportRoute,
  AcEvoSetupsNewRoute: AcEvoSetupsNewRoute,
  AcEvoSetupsIndexRoute: AcEvoSetupsIndexRoute,
  AcEvoSetupsEditTuneIdRoute: AcEvoSetupsEditTuneIdRoute,
}

const AcEvoSetupsRouteWithChildren = AcEvoSetupsRoute._addFileChildren(
  AcEvoSetupsRouteChildren,
)

interface AcEvoRouteChildren {
  AcEvoSetupsRoute: typeof AcEvoSetupsRouteWithChildren
  AcEvoIndexRoute: typeof AcEvoIndexRoute
}

const AcEvoRouteChildren: AcEvoRouteChildren = {
  AcEvoSetupsRoute: AcEvoSetupsRouteWithChildren,
  AcEvoIndexRoute: AcEvoIndexRoute,
}

const AcEvoRouteWithChildren = AcEvoRoute._addFileChildren(AcEvoRouteChildren)

interface AccSetupsRouteChildren {
  AccSetupsImportRoute: typeof AccSetupsImportRoute
  AccSetupsNewRoute: typeof AccSetupsNewRoute
  AccSetupsIndexRoute: typeof AccSetupsIndexRoute
  AccSetupsEditTuneIdRoute: typeof AccSetupsEditTuneIdRoute
}

const AccSetupsRouteChildren: AccSetupsRouteChildren = {
  AccSetupsImportRoute: AccSetupsImportRoute,
  AccSetupsNewRoute: AccSetupsNewRoute,
  AccSetupsIndexRoute: AccSetupsIndexRoute,
  AccSetupsEditTuneIdRoute: AccSetupsEditTuneIdRoute,
}

const AccSetupsRouteWithChildren = AccSetupsRoute._addFileChildren(
  AccSetupsRouteChildren,
)

interface AccRouteChildren {
  AccSetupsRoute: typeof AccSetupsRouteWithChildren
  AccIndexRoute: typeof AccIndexRoute
}

const AccRouteChildren: AccRouteChildren = {
  AccSetupsRoute: AccSetupsRouteWithChildren,
  AccIndexRoute: AccIndexRoute,
}

const AccRouteWithChildren = AccRoute._addFileChildren(AccRouteChildren)

interface F125SetupsRouteChildren {
  F125SetupsIndexRoute: typeof F125SetupsIndexRoute
}

const F125SetupsRouteChildren: F125SetupsRouteChildren = {
  F125SetupsIndexRoute: F125SetupsIndexRoute,
}

const F125SetupsRouteWithChildren = F125SetupsRoute._addFileChildren(
  F125SetupsRouteChildren,
)

interface F125TunesRouteChildren {
  F125TunesIndexRoute: typeof F125TunesIndexRoute
}

const F125TunesRouteChildren: F125TunesRouteChildren = {
  F125TunesIndexRoute: F125TunesIndexRoute,
}

const F125TunesRouteWithChildren = F125TunesRoute._addFileChildren(
  F125TunesRouteChildren,
)

interface F125RouteChildren {
  F125SetupsRoute: typeof F125SetupsRouteWithChildren
  F125TunesRoute: typeof F125TunesRouteWithChildren
  F125IndexRoute: typeof F125IndexRoute
}

const F125RouteChildren: F125RouteChildren = {
  F125SetupsRoute: F125SetupsRouteWithChildren,
  F125TunesRoute: F125TunesRouteWithChildren,
  F125IndexRoute: F125IndexRoute,
}

const F125RouteWithChildren = F125Route._addFileChildren(F125RouteChildren)

interface Fm23SetupsRouteChildren {
  Fm23SetupsCatalogRoute: typeof Fm23SetupsCatalogRoute
  Fm23SetupsNewRoute: typeof Fm23SetupsNewRoute
  Fm23SetupsIndexRoute: typeof Fm23SetupsIndexRoute
  Fm23SetupsEditTuneIdRoute: typeof Fm23SetupsEditTuneIdRoute
}

const Fm23SetupsRouteChildren: Fm23SetupsRouteChildren = {
  Fm23SetupsCatalogRoute: Fm23SetupsCatalogRoute,
  Fm23SetupsNewRoute: Fm23SetupsNewRoute,
  Fm23SetupsIndexRoute: Fm23SetupsIndexRoute,
  Fm23SetupsEditTuneIdRoute: Fm23SetupsEditTuneIdRoute,
}

const Fm23SetupsRouteWithChildren = Fm23SetupsRoute._addFileChildren(
  Fm23SetupsRouteChildren,
)

interface Fm23RouteChildren {
  Fm23SetupsRoute: typeof Fm23SetupsRouteWithChildren
  Fm23IndexRoute: typeof Fm23IndexRoute
  Fm23CarsCarOrdinalRoute: typeof Fm23CarsCarOrdinalRoute
}

const Fm23RouteChildren: Fm23RouteChildren = {
  Fm23SetupsRoute: Fm23SetupsRouteWithChildren,
  Fm23IndexRoute: Fm23IndexRoute,
  Fm23CarsCarOrdinalRoute: Fm23CarsCarOrdinalRoute,
}

const Fm23RouteWithChildren = Fm23Route._addFileChildren(Fm23RouteChildren)

interface IracingRouteChildren {
  IracingIndexRoute: typeof IracingIndexRoute
}

const IracingRouteChildren: IracingRouteChildren = {
  IracingIndexRoute: IracingIndexRoute,
}

const IracingRouteWithChildren =
  IracingRoute._addFileChildren(IracingRouteChildren)

interface LiveRouteChildren {
  LivePitRoute: typeof LivePitRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LivePitRoute: LivePitRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

interface LmuRouteChildren {
  LmuIndexRoute: typeof LmuIndexRoute
}

const LmuRouteChildren: LmuRouteChildren = {
  LmuIndexRoute: LmuIndexRoute,
}

const LmuRouteWithChildren = LmuRoute._addFileChildren(LmuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameidRoute: GameidRouteWithChildren,
  AcRoute: AcRouteWithChildren,
  AcEvoRoute: AcEvoRouteWithChildren,
  AccRoute: AccRouteWithChildren,
  DevRoute: DevRoute,
  F125Route: F125RouteWithChildren,
  Fm23Route: Fm23RouteWithChildren,
  IracingRoute: IracingRouteWithChildren,
  LiveRoute: LiveRouteWithChildren,
  LmuRoute: LmuRouteWithChildren,
  PortableCombo1Route: PortableCombo1Route,
  PortableCombo2Route: PortableCombo2Route,
  PortableIndexRoute: PortableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
