// Catalog artifact rendering, compatibility checks, and filesystem verification.

function markdownCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function cardinalityLabel(variable: CatalogVariable): string {
  const cardinality = variable.cardinality;
  if (!cardinality) return "missing";
  if (cardinality.kind === "scalar") return "scalar";
  if (cardinality.kind === "fixed") return `fixed:${cardinality.count}`;
  return `variable:${cardinality.min}-${cardinality.max ?? "*"}`;
}

function valueSchemaLabel(variable: CatalogVariable): string {
  if (variable.valueType === "enum") {
    return `domain: ${variable.enumDomain?.join(", ") ?? "missing"}`;
  }
  if (variable.valueType !== "structured" || !variable.structuredSchema) {
    return "";
  }
  const indices = variable.structuredSchema.indices
    .map(
      (index) =>
        `${index.id} (${index.cardinality.kind}:${index.cardinality.kind === "fixed" ? index.cardinality.count : index.cardinality.kind === "variable" ? `${index.cardinality.min}-${index.cardinality.max ?? "*"}` : "1"}, ${index.ordering})`,
    )
    .join("; ");
  const fields = variable.structuredSchema.fields
    .map((field) => `${field.id}:${field.valueType}`)
    .join(", ");
  return `indices: ${indices}; fields: ${fields}`;
}


function renderCatalogMarkdown(catalog: BuiltTelemetryCatalog): string {
  const lines = [
    "# Telemetry catalog",
    "",
    "> Generated by `bun run telemetry:catalog`. Do not edit manually.",
    "",
    "## Manifest",
    "",
    `- Catalog version: \`${catalog.metadata.catalogVersion}\``,
    `- Schema version: \`${catalog.metadata.schemaVersion}\``,
    `- Generator: \`${catalog.metadata.generator.name}@${catalog.metadata.generator.version}\``,
    `- Generator source SHA-256: \`${catalog.metadata.generator.sourceHash}\``,
    `- Content SHA-256: \`${catalog.metadata.contentHash}\``,
    "",
    "## Coverage",
    "",
    "| Simulator | Sources | Recorded | Packet | Extension | SDK | YAML | Setup |",
    "|---|---:|---:|---:|---:|---:|---:|---:|",
    ...GAME_IDS.map((gameId) => {
      const coverage = catalog.coverage.sourceCounts[gameId];
      return `| ${gameId} | ${coverage.total} | ${coverage.recorded} | ${coverage.packet} | ${coverage.extension} | ${coverage.sdk} | ${coverage.yaml} | ${coverage.setup} |`;
    }),
    "",
    "## Semantic variables",
    "",
    "| Semantic ID | Label | Value type | Dimensions | Unit | Cardinality | Ordering | Value schema | Limitations |",
    "|---|---|---|---|---|---|---|---|---|",
    ...catalog.variables.map(
      (variable) =>
        `| \`${markdownCell(variable.id)}\` | ${markdownCell(variable.label)} | ${variable.valueType} | ${markdownCell(variable.dimensions?.join(" × ") ?? "")} | ${markdownCell(variable.canonicalUnit)} | ${cardinalityLabel(variable)} | ${markdownCell(variable.ordering?.join(", ") ?? "")} | ${markdownCell(valueSchemaLabel(variable))} | ${markdownCell(variable.limitations?.join("; ") ?? "")} |`,
    ),
    "",
    "See [`telemetry-catalog-matrix.md`](./telemetry-catalog-matrix.md) for generated cross-simulator mappings.",
  ];
  return `${lines.join("\n")}\n`;
}

function renderMappingCell(mapping: GameLink): string {
  if (mapping.kind === "unavailable") {
    return markdownCell(`unavailable · ${mapping.reason}`);
  }
  const sources = Array.isArray(mapping.sources)
    ? mapping.sources
    : Object.entries(mapping.sources).flatMap(([element, values]) =>
        values.map((source) => `${element}:${source}`),
      );
  const details = [
    mapping.kind,
    mapping.nativeUnit,
    sources.join("<br>"),
    mapping.provenance?.artifact ?? "",
    mapping.execution?.id ?? "",
    mapping.limitations?.join("; ") ?? "",
  ].filter(Boolean);
  return markdownCell(details.join(" · "));
}

function renderCompatibilityMatrix(catalog: BuiltTelemetryCatalog): string {
  const lines = [
    "# Telemetry cross-simulator compatibility matrix",
    "",
    "> Generated by `bun run telemetry:catalog`. Do not edit manually.",
    "",
    `Catalog \`${catalog.metadata.catalogVersion}\`, schema \`${catalog.metadata.schemaVersion}\`, content \`${catalog.metadata.contentHash}\`.`,
    "",
    "| Semantic ID | Type | Dimensions | Unit | Cardinality | FM 2023 | F1 2025 | ACC | AC | AC Evo | iRacing | LMU |",
    "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ...catalog.variables.map(
      (variable) =>
        `| \`${markdownCell(variable.id)}\` | ${variable.valueType} | ${markdownCell(variable.dimensions?.join(" × ") ?? "")} | ${markdownCell(variable.canonicalUnit)} | ${cardinalityLabel(variable)} | ${renderMappingCell(variable.games["fm-2023"])} | ${renderMappingCell(variable.games["f1-2025"])} | ${renderMappingCell(variable.games.acc)} | ${renderMappingCell(variable.games.ac)} | ${renderMappingCell(variable.games["ac-evo"])} | ${renderMappingCell(variable.games.iracing)} | ${renderMappingCell(variable.games.lmu)} |`,
    ),
  ];
  return `${lines.join("\n")}\n`;
}

function renderTypeUnion(values: readonly string[]): string {
  if (values.length === 0) return "never";
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

function renderCatalogTypes(catalog: BuiltTelemetryCatalog): string {
  const groupIds = [...new Set(catalog.groups.map((group) => group.id))].sort();
  const variableIds = [...new Set(catalog.variables.map((variable) => variable.id))].sort();
  const sourcePaths = Object.fromEntries(
    GAME_IDS.map((gameId) => [
      gameId,
      [...new Set(catalog.sources[gameId].map((source) => source.path))].sort(),
    ]),
  ) as Record<(typeof GAME_IDS)[number], string[]>;
  const mappingSourcePaths = Object.fromEntries(
    GAME_IDS.map((gameId) => [
      gameId,
      [
        ...new Set(
          catalog.variables.flatMap((variable) => {
            const mapping = variable.games[gameId];
            if (mapping.kind === "unavailable") return [];
            return Array.isArray(mapping.sources)
              ? mapping.sources
              : Object.values(mapping.sources).flat();
          }),
        ),
      ].sort(),
    ]),
  ) as Record<(typeof GAME_IDS)[number], string[]>;
  const renderPathMap = (paths: Record<(typeof GAME_IDS)[number], string[]>) =>
    GAME_IDS.map(
      (gameId) => `  ${JSON.stringify(gameId)}: ${renderTypeUnion(paths[gameId])};`,
    ).join("\n");
  return [
    "// Generated by packages/tooling-catalog/src/catalog/generate-telemetry-catalog.ts. Do not edit.",
    'import type { GameId } from "../../../games/ids";',
    "",
    `export type TelemetryGroupId = ${renderTypeUnion(groupIds)};`,
    `export type TelemetryVariableId = ${renderTypeUnion(variableIds)};`,
    "export type TelemetryNodeId = TelemetryGroupId | TelemetryVariableId;",
    "",
    "export type TelemetrySourcePathByGame = {",
    renderPathMap(sourcePaths),
    "};",
    "",
    "export type TelemetryMappingSourcePathByGame = {",
    renderPathMap(mappingSourcePaths),
    "};",
    "",
    "export type TelemetrySourcePath<G extends GameId> = TelemetrySourcePathByGame[G];",
    "export type TelemetryMappingSourcePath<G extends GameId> = TelemetryMappingSourcePathByGame[G];",
    "",
  ].join("\n");
}

export async function buildTelemetryCatalogArtifacts(): Promise<
  ReadonlyMap<string, string>
> {
  const catalog = await buildTelemetryCatalog();
  const json = `${JSON.stringify(catalog, null, 2)}\n`;
  const generatedTypeScript = [
    "// Generated by packages/tooling-catalog/src/catalog/generate-telemetry-catalog.ts. Do not edit.",
    'import catalog from "./telemetry-catalog.generated.json";',
    "",
    `export const TELEMETRY_CATALOG_VERSION = ${JSON.stringify(catalog.metadata.catalogVersion)};`,
    `export const TELEMETRY_CATALOG_SCHEMA_VERSION = ${JSON.stringify(catalog.metadata.schemaVersion)};`,
    `export const TELEMETRY_CATALOG_HASH = ${JSON.stringify(catalog.metadata.contentHash)};`,
    "export const TELEMETRY_CATALOG_GENERATED = catalog;",
    "",
  ].join("\n");
  return new Map([
    [OUTPUT_PATH, json],
    [OUTPUT_TS_PATH, generatedTypeScript],
    [OUTPUT_TYPES_PATH, renderCatalogTypes(catalog)],
    [OUTPUT_MARKDOWN_PATH, renderCatalogMarkdown(catalog)],
    [OUTPUT_MATRIX_PATH, renderCompatibilityMatrix(catalog)],
  ]);
}

type CompatibilityCatalogMapping = {
  kind?: unknown;
  compatibilityReview?: unknown;
};

type CompatibilityCatalogVariable = {
  id: string;
  games: Record<string, CompatibilityCatalogMapping>;
};

function recordValue(value: unknown): Record<string, unknown> | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function compatibilityVariables(
  catalog: unknown,
  label: string,
  allowMissingGameMappings = false,
): readonly CompatibilityCatalogVariable[] {
  const root = recordValue(catalog);
  if (!root || !Array.isArray(root.variables)) {
    throw new Error(`${label} telemetry catalog lacks a variables array`);
  }
  const result: CompatibilityCatalogVariable[] = [];
  const seen = new Set<string>();
  for (const rawVariable of root.variables) {
    const variable = recordValue(rawVariable);
    const games = recordValue(variable?.games);
    if (
      !variable ||
      typeof variable.id !== "string" ||
      variable.id.trim().length === 0 ||
      !games
    ) {
      throw new Error(
        `${label} telemetry catalog contains a variable without id/games`,
      );
    }
    if (seen.has(variable.id)) {
      throw new Error(
        `${label} telemetry catalog contains duplicate variable ${variable.id}`,
      );
    }
    seen.add(variable.id);
    const parsedGames: Record<string, CompatibilityCatalogMapping> = {};
    for (const gameId of GAME_IDS) {
      const rawMapping = games[gameId];
      if (allowMissingGameMappings && rawMapping === undefined) continue;
      const mapping = recordValue(rawMapping);
      if (
        !mapping ||
        !["direct", "normalized", "derived", "simplified", "unavailable"].includes(
          typeof mapping.kind === "string" ? mapping.kind : "",
        )
      ) {
        throw new Error(
          `${label} telemetry catalog variable ${variable.id} has invalid ${gameId} mapping`,
        );
      }
      parsedGames[gameId] = mapping;
    }
    result.push({ id: variable.id, games: parsedGames });
  }
  return result;
}

function hasCompatibilityReview(mapping: CompatibilityCatalogMapping): boolean {
  const review = recordValue(mapping.compatibilityReview);
  return (
    typeof review?.id === "string" &&
    review.id.trim().length > 0 &&
    typeof review.rationale === "string" &&
    review.rationale.trim().length > 0
  );
}

export function assertDirectToSimplifiedCompatibilityReviews(
  currentCatalog: unknown,
  baselineCatalog: unknown,
): void {
  const current = compatibilityVariables(currentCatalog, "Current");
  const baseline = new Map(
    compatibilityVariables(baselineCatalog, "Baseline", true).map((variable) => [
      variable.id,
      variable,
    ]),
  );
  const missing: string[] = [];
  for (const variable of current) {
    const previous = baseline.get(variable.id);
    if (!previous) continue;
    for (const gameId of GAME_IDS) {
      const currentMapping = variable.games[gameId];
      const previousMapping = previous.games[gameId];
      if (
        previousMapping?.kind === "direct" &&
        currentMapping?.kind === "simplified" &&
        !hasCompatibilityReview(currentMapping)
      ) {
        missing.push(`${variable.id} [${gameId}]`);
      }
    }
  }
  if (missing.length > 0) {
    missing.sort();
    throw new Error(
      [
        "Direct-to-simplified telemetry mappings require explicit compatibilityReview { id, rationale }:",
        ...missing.map((mapping) => `- ${mapping}`),
      ].join("\n"),
    );
  }
}


async function readBaselineCatalog(path: string): Promise<unknown> {
  let source: string;
  try {
    source = await readFile(resolve(ROOT, path), "utf8");
  } catch (error) {
    throw new Error(`Unable to read telemetry catalog baseline ${path}`, {
      cause: error,
    });
  }
  try {
    return JSON.parse(source);
  } catch (error) {
    throw new Error(`Invalid telemetry catalog baseline JSON ${path}`, {
      cause: error,
    });
  }
}

async function verifyArtifacts(
  expected: ReadonlyMap<string, string>,
): Promise<void> {
  for (const [path, content] of expected) {
    let actual: string;
    try {
      actual = await readFile(path, "utf8");
    } catch {
      throw new Error(`Missing generated telemetry catalog artifact ${path}`);
    }
    if (actual !== content) {
      throw new Error(
        `Stale telemetry catalog artifact ${path}; run bun run telemetry:catalog`,
      );
    }
  }
}
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  GAME_IDS,
  OUTPUT_MARKDOWN_PATH,
  OUTPUT_MATRIX_PATH,
  OUTPUT_PATH,
  OUTPUT_TS_PATH,
  OUTPUT_TYPES_PATH,
  ROOT,
} from "./model";
import type {
  BuiltTelemetryCatalog,
  CatalogVariable,
  GameLink,
} from "./model";
import { buildTelemetryCatalog } from "./generate-telemetry-catalog";
export {
  renderCatalogMarkdown,
  renderCompatibilityMatrix,
  verifyArtifacts,
  readBaselineCatalog,
};
